[project]
name = "cloudfs"
version = "0.2.0"
description = "An interface to interact with cloud storage as if it's a local filesystem."
authors = [{ name = "Allen Chou", email = "f1470891079@gmail.com" }]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = []

[project.optional-dependencies]
google = ["google-cloud-storage>=3,<4"]
s3 = ["boto3>=1.35,<2"]
all = ["google-cloud-storage>=3,<4", "boto3>=1.35,<2"]

[dependency-groups]
dev = [
    "pytest",
    "flake8",
    "black",
    "isort",
    "flake8-pyproject",
    "poetry-plugin-export",
    "python-dotenv",
]

[tool.black]
target-version = ["py311"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]

[tool.isort]
profile = "black"
line_length = 88

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
